library(tidyverse)
library(httr)
library(jsonlite)


key <- read_file('github_key.txt')
url <- "https://api.github.com/repos/nathanhwangbo/shiny-demo/issues"


text <- toJSON(
  list(
    title = unbox("test title"),
    body = unbox("this was generated by an R script"),
    labels = "shiny comment" # note that this is custom. Only allowed if you have write access to the repo
    ),
  pretty =TRUE
  )


POST(url, body = text, config = authenticate(user = 'dummy', password = key))










  
  